-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  key_hash text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  permissions jsonb NOT NULL DEFAULT '["read"]'::jsonb,
  rate_limit integer DEFAULT 1000,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid,
  staff_id uuid NOT NULL,
  service_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::appointment_status,
  scheduled_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  price integer NOT NULL CHECK (price >= 0),
  currency text NOT NULL DEFAULT 'ARS'::text,
  notes text,
  internal_notes text,
  cancellation_reason USER-DEFINED,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  completed_at timestamp with time zone,
  reminder_sent_at timestamp with time zone,
  reminder_24h_sent boolean DEFAULT false,
  reminder_1h_sent boolean DEFAULT false,
  source text DEFAULT 'web'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_id uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT appointments_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT appointments_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id),
  CONSTRAINT appointments_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.users(id),
  CONSTRAINT appointments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  business_id uuid,
  action USER-DEFINED NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  changed_fields ARRAY,
  ip_address inet,
  user_agent text,
  context jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT audit_logs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.blocked_times (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  staff_id uuid,
  title text NOT NULL,
  description text,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  is_recurring boolean NOT NULL DEFAULT false,
  recurrence_rule text,
  recurrence_end_date date,
  block_type text NOT NULL DEFAULT 'blocked'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blocked_times_pkey PRIMARY KEY (id),
  CONSTRAINT blocked_times_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT blocked_times_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT blocked_times_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.business_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_open boolean NOT NULL DEFAULT true,
  open_time time without time zone NOT NULL DEFAULT '09:00:00'::time without time zone,
  close_time time without time zone NOT NULL DEFAULT '19:00:00'::time without time zone,
  CONSTRAINT business_hours_pkey PRIMARY KEY (id),
  CONSTRAINT business_hours_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  type USER-DEFINED NOT NULL DEFAULT 'other'::business_type,
  status USER-DEFINED NOT NULL DEFAULT 'pending_setup'::business_status,
  description text,
  logo_url text,
  cover_image_url text,
  phone text,
  email text,
  website text,
  address jsonb DEFAULT '{"city": "", "state": "", "number": "", "street": "", "country": "Argentina", "latitude": null, "apartment": "", "longitude": null, "postalCode": ""}'::jsonb,
  settings jsonb NOT NULL DEFAULT '{"language": "es", "timezone": "America/Argentina/Buenos_Aires", "sendReminders": true, "defaultCurrency": "ARS", "allowOnlineBooking": true, "reminderHoursBefore": 24, "requireConfirmation": false, "maxAdvanceBookingDays": 30, "minAdvanceBookingHours": 2, "cancellationPolicyHours": 24}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT fk_businesses_owner FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  full_name text NOT NULL,
  email text,
  phone text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.login_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  ip_address inet NOT NULL,
  user_agent text,
  success boolean NOT NULL,
  failure_reason text,
  country_code text,
  is_suspicious boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT login_attempts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  business_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id uuid,
  data jsonb DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  sent_at timestamp with time zone,
  channel USER-DEFINED NOT NULL DEFAULT 'in_app'::notification_channel,
  send_attempts integer DEFAULT 0,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  staff_id uuid NOT NULL,
  business_id uuid NOT NULL,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  response text,
  responded_at timestamp with time zone,
  responded_by uuid,
  is_visible boolean NOT NULL DEFAULT true,
  is_verified boolean NOT NULL DEFAULT false,
  reported_at timestamp with time zone,
  reported_reason text,
  moderated_at timestamp with time zone,
  moderated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT reviews_responded_by_fkey FOREIGN KEY (responded_by) REFERENCES public.users(id),
  CONSTRAINT reviews_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT reviews_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT reviews_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT reviews_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.users(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  category USER-DEFINED NOT NULL DEFAULT 'other'::service_category,
  duration_minutes integer NOT NULL CHECK (duration_minutes >= 5 AND duration_minutes <= 480),
  price integer NOT NULL CHECK (price >= 0),
  currency text NOT NULL DEFAULT 'ARS'::text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::service_status,
  image_url text,
  sort_order integer NOT NULL DEFAULT 0,
  requires_deposit boolean NOT NULL DEFAULT false,
  deposit_amount integer CHECK (deposit_amount IS NULL OR deposit_amount > 0),
  settings jsonb DEFAULT '{"maxConcurrent": 1, "allowOnlineBooking": true, "requiresConfirmation": false}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  business_id uuid NOT NULL,
  title text,
  bio text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::staff_status,
  break_duration_minutes integer NOT NULL DEFAULT 10 CHECK (break_duration_minutes >= 0),
  max_daily_appointments integer CHECK (max_daily_appointments IS NULL OR max_daily_appointments > 0),
  color text NOT NULL DEFAULT '#8b5cf6'::text CHECK (color ~* '^#[0-9A-Fa-f]{6}$'::text),
  sort_order integer NOT NULL DEFAULT 0,
  stats jsonb DEFAULT '{"totalReviews": 0, "averageRating": null, "totalAppointments": 0, "completedAppointments": 0}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT staff_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.staff_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  service_id uuid NOT NULL,
  custom_price integer CHECK (custom_price IS NULL OR custom_price >= 0),
  custom_duration integer CHECK (custom_duration IS NULL OR custom_duration >= 5),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_services_pkey PRIMARY KEY (id),
  CONSTRAINT staff_services_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT staff_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.staff_time_slots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_working_hours_id uuid NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  CONSTRAINT staff_time_slots_pkey PRIMARY KEY (id),
  CONSTRAINT staff_time_slots_staff_working_hours_id_fkey FOREIGN KEY (staff_working_hours_id) REFERENCES public.staff_working_hours(id)
);
CREATE TABLE public.staff_working_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_working boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_working_hours_pkey PRIMARY KEY (id),
  CONSTRAINT staff_working_hours_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  appointment_id uuid,
  client_id uuid,
  staff_id uuid,
  type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::transaction_status,
  amount integer NOT NULL CHECK (amount > 0),
  currency text NOT NULL DEFAULT 'ARS'::text,
  payment_method USER-DEFINED NOT NULL,
  description text,
  reference text,
  original_transaction_id uuid,
  refund_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT transactions_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT transactions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT transactions_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT transactions_original_transaction_id_fkey FOREIGN KEY (original_transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token_hash text NOT NULL,
  refresh_token_hash text,
  device_info jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  is_valid boolean NOT NULL DEFAULT true,
  last_activity_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  revoked_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  role USER-DEFINED NOT NULL DEFAULT 'client'::user_role,
  status USER-DEFINED NOT NULL DEFAULT 'pending_verification'::user_status,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text CHECK (phone IS NULL OR phone ~* '^\+?[0-9\s\-\(\)]{8,20}$'::text),
  avatar_url text,
  business_id uuid,
  email_verified_at timestamp with time zone,
  last_login_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  failed_login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  preferences jsonb DEFAULT '{"theme": "system", "language": "es", "notifications": {"sms": false, "push": true, "email": true}}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);